### PR TITLE
Add BACKLOG.md to track user-reported enhancement requests

### PR DESCRIPTION
**Pull request by alexng-canuck**
This will help us declutter the github issues list and allow it to
focus on bugs and blocking issues. This also gives us a way to
uniformly track and provide updates on these requested enhancements.

Enhancements coming from github issues list can be closed, once
they are tracked here.

### CODE REVIEW

**Comment by codycushing** [comment]
This structure looks mostly fine, I dont think we should include an eta column. 

I believe this is something we should manage in a wiki page in this repo so that updates don't require the PR and commit process.

**Comment by alexng-canuck** [comment]
@codycushing Fair point. Had this PR ready before realizing that we could just copy this over to the wiki.

**Comment by anandhmahal** [comment]
@alexng-canuck - It would be nice if you can add a column for the GitHub issues ID. It would be easy to compare the IDs as opposed to the descriptions, when we cross check.

**Comment by alexng-canuck** [comment]
Moving this backlog into the wiki instead: https://github.com/oracle/terraform-provider-oci/wiki/Feature-Request-and-Enhancements-Backlog

**Pull request closed without merging**
