### PR TITLE
chore: fix an issue with debug statement

### PR DESCRIPTION
**Pull request by karanssh**
This looks like some debug statement that made way into commit to master. Cleaned up and removed.

it's annoying when running the tool.

### CODE REVIEW

**Comment by karanssh** [comment]
Well I have signed it, and the application is "under process".

**Comment by tf-oci-pub** [comment]
Thank you for your valuable contribution. We greatly appreciate your efforts in submitting this pull request. However, I regret to inform you that we are unable to merge it directly on GitHub at this time.

Our internal policy requires that all pull requests undergo thorough local testing and review before they can be merged into the main codebase. This process ensures the quality and stability of Terraform-Provider-OCI.

We understand that this may cause some inconvenience, but please rest assured that your contribution is highly valued. Our team will carefully review and test your changes locally to ensure they meet our standards.

We appreciate your understanding and patience in this matter. If you have any questions or need further assistance, please don't hesitate to reach out. Thank you once again for your contribution.

**Review by ravinitp — APPROVED** [review]
Thanks for your contribution. This change will be available in next release.

**Comment by NagendraNigade** [comment]
@karanssh Thank you for raising this PR. Unfortunately we cant run this PR directly due to test validation to be taken care before. We will open a tracking ticket internally to merge this changes. Thank you.

**Pull request closed without merging**
