### PR TITLE
Update core_internet_gateway.html.markdown

### PR DESCRIPTION
**Pull request by taro7506**
delete duplicated text.

Please let me know if I misunderstanding how to contribute!
(The link for [The Oracle Contributor Agreement](https://www.oracle.com/technetwork/community/oca-486395.html) in [CONTRIBUTING.md](https://github.com/oracle/terraform-provider-oci/blob/master/CONTRIBUTING.md) seems to be dead.)

Thank you!

### CODE REVIEW

**Review by jotruon — APPROVED** [review]

**Comment by tf-oci-pub** [comment]
Thank you for your valuable contribution. We greatly appreciate your efforts in submitting this pull request. However, I regret to inform you that we are unable to merge it directly on GitHub at this time.

Our internal policy requires that all pull requests undergo thorough local testing and review before they can be merged into the main codebase. This process ensures the quality and stability of Terraform-Provider-OCI.

We understand that this may cause some inconvenience, but please rest assured that your contribution is highly valued. Our team will carefully review and test your changes locally to ensure they meet our standards.

We appreciate your understanding and patience in this matter. If you have any questions or need further assistance, please don't hesitate to reach out. Thank you once again for your contribution.

**Comment by Maxrovr** [comment]
@taro7506 Why is this update required?

**Comment by taro7506** [comment]
@Maxrovr 
It's just a duplicate notation fix.(It may also be an error on terraform.)

https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_internet_gateway

**Comment by niskulka71** [comment]
Resolution for this issue has been released in version 5.9.0

**Pull request closed without merging**
