### PR TITLE
IPSec Tunnel Management Phase Configuration

### PR DESCRIPTION
**Pull request by xpalou0**
This PR adds support to oci_core_ipsec_connection_tunnel_management resource to configure phase_one and phase_two. Relates to #1692.

Additionally marked shared_secret sensitive. Relates to #1675.

Updated documentation, so it show what could been set prior aswell to this PR.

### CODE REVIEW

**Comment by ravinitp** [comment]
Thank you for your valuable contribution. We greatly appreciate your efforts in submitting this pull request. However, I regret to inform you that we are unable to merge it directly on GitHub at this time.

Our internal policy requires that all pull requests undergo thorough local testing and review before they can be merged into the main codebase. This process ensures the quality and stability of Terraform-Provider-OCI.

We understand that this may cause some inconvenience, but please rest assured that your contribution is highly valued. Our team will carefully review and test your changes locally to ensure they meet our standards.

We appreciate your understanding and patience in this matter. If you have any questions or need further assistance, please don't hesitate to reach out. Thank you once again for your contribution.

**Comment by iejones** [comment]
I am working on updating the oci_core_ipsec_connection_tunnel_managment resources for issues address in this pr request and others.
-     add tunnel phase 1 and 2 configurations
-     mark shared_secret sensitive
-     add validation of enum strings
-     make tunnel management resource id composite
I still need to test the composite id for resource discoverability and backwards compatibility before internal review.

**Comment by iejones** [comment]
A fix with the following changes requested in this PR will be released on November 15th, 2023
- add tunnel phase 1 and 2 configurations
- mark shared_secret sensitive
- add validation of enum strings

**Comment by iejones** [comment]
This fix was released with version [v5.21.0](https://github.com/oracle/terraform-provider-oci/releases/tag/v5.21.0)

**Pull request closed without merging**
